{% set name = "qikpropservice" %}
{% set version = "0.2.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 66a03d09fba1402cf8ddd361ccb3b42452e6320dfc83d10716e8e466875b9d89

build:
  noarch: python
  number: 1
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - qikpropcli = qikpropservice:qpcli

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - requests
    - click
    - pydantic
    - tqdm

test:
  requires:
    - python {{ python_min }}
  imports:
    - qikpropservice
  commands:
    - qikpropcli --help

about:
  home: https://github.com/MolSSI/qikpropservice
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: MolSSI QikProp As A Service API Wrapper Library
  description: |
    The qikpropservice library wraps the API calls for the QikProp v3 As A Service
    providing both the CLI and the library capability to call the Service hosted
    by the Molecular Sciences Software Institute. The version of QikProp 
    provided as a service has been provided by 
    William L. Jorgensen <http://zarbi.chem.yale.edu/> in agreement with
    Schrödinger <https://www.schrodinger.com/>.
  doc_url: https://github.com/MolSSI/qikpropservice
  dev_url: https://github.com/MolSSI/qikpropservice

extra:
  recipe-maintainers:
    - lnaden
